### ISSUE TITLE
No Track Dependency API?

### ISSUE THREAD

**Issue by boarmanc** [Microsoft/ApplicationInsights-PHP#18]
Is this project actively maintained by Microsoft? I do not see any support for the TrackDependency method of Telemetry Client:
https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#track-dependency
Is there any plan to add this?
Thanks

**Comment by JakubOleksy** [comment]
We don't currently have any plans to add this. The SDK is currently supported on a best-effort basis but isn't actively being developed. We're happy to take PRs though.
