### ISSUE TITLE
Duration in app insights off by a factor or 10 for trackPageView?

### ISSUE THREAD

**Issue by AndrewLane** [Microsoft/ApplicationInsights-PHP#30]
Let me know if I'm crazy, but if I do

trackPageView("page", "url", 1284)

which I assume would mean 1.284 seconds, I'm seeing

.1284 seconds as the duration in app insights.

**Comment by fadamsen** [comment]
It doesn't look like `trackPageView` converts its duration to the `DD.HH:MM:SS.UUUUUU` format expected by Application Insights, so perhaps it ends up being parsed as a number of microseconds? That would be consistent with what you're seeing.
