### ISSUE TITLE
Release recent changes

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/ApplicationInsights-PHP#33]
@JakubOleksy Could you please publish the actual version so we can use message severity level and authenticated user id from Composer? Thanks.

**Comment by JakubOleksy** [comment]
I am not sure what you mean, but if you want to do a pull request, I can review.

**Comment by Peter-Juhasz** [comment]
I meant Packagist, not Composer at the end. https://packagist.org/packages/microsoft/application-insights - it seems like this package was updated in February, so it does not contain the features we added in May. Could you update this, please?

**Comment by JakubOleksy** [comment]
Got it. Done!
