### ISSUE TITLE
App Ins - PHP webapp

### ISSUE THREAD

**Issue by SajalGolas** [Microsoft/ApplicationInsights-PHP#39]
Hi All,

I need some assistance.

Well, I have configured AppIns with an PHP WebApp using **Instrumentation** **Key** as shown in this page. 
Now, my requirement is to see -
1. Which page of the website gets the most request/hits in a graph.
2. Which page of the website gets the less response or takes time to load or refresh.

Any lead or help will be highly appreciated. Thank you in advance.

**Comment by JakubOleksy** [comment]
Have you looked at your dashboard in the Azure Portal? Have you read through the App Insights [documentation](https://docs.microsoft.com/en-us/azure/application-insights/)?

**Comment by monitarvind** [comment]
hi Jakub,

thanks for the reply. Yes, I have gone through the documentation and tried to change the metric parameters. Please refer to the screenshot.

this is what im getting.
![image](https://user-images.githubusercontent.com/27819239/36523845-88bb6afe-17c9-11e8-91be-d675e5d7016b.png)

And, im using this PHP command to receive telemetry from my webapp:
Sending a simple page view telemetry item with page name and url:
$telemetryClient->trackPageView('myPageView', 'http://www.foo.com');
$telemetryClient->flush();

Is this command sufficient to receive all the page related telemetry?
Please guide me through, im new to this.

regards,
monit

PS- im also reachable on monit.kk@gmail.com

**Comment by JakubOleksy** [comment]
Doesn't look like any data is being sent. Can you see any page views?

**Comment by JakubOleksy** [comment]
I would suggest you ask your questions in the Application Insights forums. I think you'll have to log custom data to do this.

**Comment by mrdemc** [comment]
$telemetryClient->trackPageView('myPageView', 'http://www.foo.com'.$_SERVER['REQUEST_URI']);
Or something similar should do the trick. You are passing the same url each time that function is ran.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#page-views

**Comment by SergeyKanzhelev** [comment]
@mrdemc you can always use [analytics](https://docs.microsoft.com/azure/application-insights/app-insights-analytics). Query like this `pageViews | summarize avg(duration) by name` will group response time by name. 

Closing for now - feel free to reopen
