### ISSUE TITLE
Operation name is empty

### ISSUE THREAD

**Issue by jjindrich** [Microsoft/ApplicationInsights-PHP#54]
When I run trackRequest with trackDependency, all data are submitted in AI database successfully. But there is missing Operation Name, Id in database. The efect of this is that on Azure portal in Performance blade are Operations missing. I was comparing data sent from .Net project and there is Operation reported correctly.
Is there any workaround how to setup Operation ?

**Comment by jondmcelroy** [comment]
Thats why I made this PR #51

**Comment by jjindrich** [comment]
I created new PR #55 to update documentation

**Comment by SergeyKanzhelev** [comment]
Is the issue on how to report the name or that it needs to be also populated automatically? Please rename the issue or I can close it
