### ISSUE TITLE
Release 0.4.5

### ISSUE THREAD

**Issue by norzechowicz** [Microsoft/ApplicationInsights-PHP#66]
Hey, is there any chance to draft new release 0.4.5? 
In release [0.4.4 Telemetry_Client::trackMetric](https://github.com/Microsoft/ApplicationInsights-PHP/blob/b528e31668b99e90cd498fc37a5c850c764c6d7d/ApplicationInsights/Telemetry_Client.php#L92) method is broken, it's using uppercase constant name `Channel\Contracts\Data_Point_Type::AGGREGATION` but it suppose to be lowercase [0.4.4 
Data_Point_Type::Aggregation](https://github.com/Microsoft/ApplicationInsights-PHP/blob/b528e31668b99e90cd498fc37a5c850c764c6d7d/ApplicationInsights/Channel/Contracts/Data_Point_Type.php#L17).

It looks that this was already fixed in [master Telemetry_Client::trackMetric](https://github.com/Microsoft/ApplicationInsights-PHP/blob/master/ApplicationInsights/Telemetry_Client.php#L92) but because I'm building [Symfony Bundle for App Insights](https://github.com/app-insights-php/app-insights-php-bundle) I can't simply update dependency to `"*"`. 

Thanks!

**Comment by norzechowicz** [comment]
https://github.com/Microsoft/ApplicationInsights-PHP/issues/59 - is asking about the same thing

**Comment by SergeyKanzhelev** [comment]
Sorry for delay

**Comment by norzechowicz** [comment]
Awesome, thanks @SergeyKanzhelev 🍻
