### ISSUE TITLE
Support for newer version of Guzzle

### ISSUE THREAD

**Issue by hajekj** [Microsoft/ApplicationInsights-PHP#9]
Is it possible for the library to support Guzzle 6.*? I cannot have this co-exist with other libraries. Which depend on Guzzle 6.

**Comment by hajekj** [comment]
Just tested and it works just fine, submitting a pull request.

**Comment by hajekj** [comment]
Pull request: https://github.com/Microsoft/ApplicationInsights-PHP/pull/10

**Comment by JakubOleksy** [comment]
Just merged it. Thanks!
